spec:
  rules:
    - host: "{{ index .Values.ingress.hosts 0 "host" }}"
      http:
        paths:
          - path: {{ index (index .Values.ingress.hosts 0).paths 0 "path" }}
            pathType: {{ index (index .Values.ingress.hosts 0).paths 0 "pathType" }}
            backend:
              service:
                name: {{ include "myapp.fullname" . }}
                port:
                  number: {{ .Values.service.port }}